[package]
name = "share_daemon"
version = "0.1.0"
edition = "2021"

[lib]
name = "fshare_server"
path = "src/lib.rs"
crate-type = ["rlib"]

[[bin]]
name = "share_daemon"
path = "src/main.rs"



[dependencies]
# uuid = {version = "*", features = ["v4", "fast-rng"] }
serde = { version = "*", features = ["derive"]}
# crossbeam = "*"
toml = "*"
chrono = "*"
tokio = { version = "*", features = ["rt", "rt-multi-thread", "net", "fs", "io-util"] }
interprocess = {version = "*", features = ["tokio"]}
ctrlc = "*"
# sha2 = "*"
# hex = "*"
# constcat = "*"
const_format = "*"
# tinystr = "*"

# [target.x86_64-pc-windows-msvc.dependencies]
# windows-sys = { version = "0.52.0", features = [
#     "Win32_Foundation",
#     "Win32_Security",
# ] }
