[package]
name = "share"
version = "0.1.0"
edition = "2021"

[dependencies]
share_daemon = { path = "../share_daemon" }
color-print = "*"
clap = { workspace = true }
anyhow = { workspace = true }
smol_str = { workspace = true }
interprocess = { workspace = true }
